services:
  db:
    image: postgres:16
    container_name: evobike-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: evobike
    ports:
      - "5433:5432"
    volumes:
      - evobike_pgdata:/var/lib/postgresql/data

volumes:
  evobike_pgdata:
